apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sidecar-demo.yaml
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    name: sidecar-demo
  spec:
    replicas: 0
    selector:
      app: sidecar-demo
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: sidecar-demo
      spec:
        containers:
        - args:
          - while true; do echo "{\"data\":\"test $(date)\"}" >> /mnt/logdir/logfile.txt;
            sleep 5; done
          command:
          - /bin/sh
          - -c
          image: docker.io/centos:7
          imagePullPolicy: Always
          name: log-producer
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/logdir
            name: logdir
        - image: docker.io/jnordell/fluentbit-sidecar
          imagePullPolicy: Always
          name: fluentbit-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/logdir
            name: logdir
            readOnly: true
          - mountPath: /fluent-bit/etc/
            name: fluentbit-config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: logdir
        - configMap:
            defaultMode: 420
            name: fluent-bit-config
          name: fluentbit-config
    test: false
    triggers: []
- apiVersion: v1
  data:
    fluent-bit.conf: |-
      [SERVICE]
          Flush         1
          Log_Level     debug
          Daemon        off
          Parsers_File  parsers.conf
      [INPUT]
          Name   tail
          Path   /mnt/logdir/logfile.txt
          Tag           kube.*
          Mem_Buf_Limit 10MB
          Key           logfile
      [FILTER]
          Name           kubernetes
          Match          *
          Merge_JSON_Log On
      [OUTPUT]
          Name            es
          Match           *
          Host            elasticsearch-logserver.192.168.99.100.nip.io
          Port            80
          Logstash_Format On
          Retry_Limit     False
    parsers.conf: |
      [PARSER]
          Name   apache
          Format regex
          Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
          Time_Key time
          Time_Format %d/%b/%Y:%H:%M:%S %z
      [PARSER]
          Name   apache2
          Format regex
          Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
          Time_Key time
          Time_Format %d/%b/%Y:%H:%M:%S %z
      [PARSER]
          Name   apache_error
          Format regex
          Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
      [PARSER]
          Name   nginx
          Format regex
          Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
          Time_Key time
          Time_Format %d/%b/%Y:%H:%M:%S %z
      [PARSER]
          Name   json-test
          Format json
          Time_Key time
          Time_Format %d/%b/%Y:%H:%M:%S %z
      [PARSER]
          Name        docker
          Format      json
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
          Time_Keep   On
      [PARSER]
          Name        syslog
          Format      regex
          Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
          Time_Key    time
          Time_Format %b %d %H:%M:%S
      [PARSER]
          Name test
          Format regex
          Regex (?<STRING>.+)$
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: fluent-bit
    name: fluent-bit-config
